### ISSUE TITLE
Quick sort for Repo

### ISSUE THREAD

**Issue by rajraii** [kumarnurav9811/Hactoberfest2021-Cpp#74]
I will be providing a detailed explained code for quick sort with easy to understand language.

**Comment by bhutani2002** [comment]
Hey @kumarnurav9811 , the Quick Sort request that you merged of mine. After the inspection of I guess 10 to 11 days, its showing that ,"The pull request was submitted to the repository that does not follow the values of hactoberfest". Please check it, as my pull request is not counted for the hactoberfest, now.
